import { ClerkProvider } from '@clerk/nextjs'
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const roboto = Roboto({ 
  subsets: ["latin"],
  weight: ['400', '500', '700']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
          <body className={roboto.className}>
            <Navbar />
            {children}
            <Footer />
          </body>
        </html>
    </ClerkProvider>
     
  );
}
